### Pandas-DataFrame And Series

In [2]:
## series 

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series\n",series);
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [3]:
## create a series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [7]:
## Dataframe
## create a DataFrame from a dicionary of list

data={
    'Name':['Abdul','Rahman','Ayyan'],
    'Age':[21,23,20],
    'City':['Bangalore','New York','florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0   Abdul   21  Bangalore
1  Rahman   23   New York
2   Ayyan   20    florida
<class 'pandas.DataFrame'>

In [9]:
import numpy as np
np.array(df)

array([['Abdul', 21, 'Bangalore'],
       ['Rahman', 23, 'New York'],
       ['Ayyan', 20, 'florida']], dtype=object)

In [10]:
print(df)

     Name  Age       City
0   Abdul   21  Bangalore
1  Rahman   23   New York
2   Ayyan   20    florida

In [12]:
## create a data frame from a list of dictionaries
data=[
    {'Name':'Abdul','Age':32,'City':'Bangalore'},
    {'Name':'Rahman','Age':22,'City':'Bangalore'},
    {'Name':'Ayyan','Age':42,'City':'Bangalore'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0   Abdul   32  Bangalore
1  Rahman   22  Bangalore
2   Ayyan   42  Bangalore
<class 'pandas.DataFrame'>

In [15]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [16]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [17]:
### Accessing data from data frame
data=[
    {'Name':'Abdul','Age':32,'City':'Bangalore'},
    {'Name':'Rahman','Age':22,'City':'Bangalore'},
    {'Name':'Ayyan','Age':42,'City':'Bangalore'}
]
df=pd.DataFrame(data)
print(df)

     Name  Age       City
0   Abdul   32  Bangalore
1  Rahman   22  Bangalore
2   Ayyan   42  Bangalore

In [18]:
df['Name']

0     Abdul
1    Rahman
2     Ayyan
Name: Name, dtype: str

In [19]:
type(df['Name'])

pandas.Series

In [20]:
df.loc[0]

Name        Abdul
Age            32
City    Bangalore
Name: 0, dtype: object

In [28]:
## Accessing a specified element
df['Name']

0     Abdul
1    Rahman
2     Ayyan
Name: Name, dtype: str

In [29]:
df

     Name  Age       City
0   Abdul   32  Bangalore
1  Rahman   22  Bangalore
2   Ayyan   42  Bangalore

In [31]:
df.at[2,'Age']

np.int64(42)

In [34]:
df.at[1,'Name']

'Rahman'

In [39]:
## accessing a specified element using iat
df.iat[1,1]

np.int64(22)

In [40]:
## Data Manuplation with dataframe
df

     Name  Age       City
0   Abdul   32  Bangalore
1  Rahman   22  Bangalore
2   Ayyan   42  Bangalore

In [41]:
df['Salary']=[50000,60000,70000]

In [42]:
df

     Name  Age       City  Salary
0   Abdul   32  Bangalore   50000
1  Rahman   22  Bangalore   60000
2   Ayyan   42  Bangalore   70000

In [43]:
## remove a column
df.drop('Salary',axis=0)

KeyError: "['Salary'] not found in axis"

In [44]:
df.drop('Salary',axis=1)

     Name  Age       City
0   Abdul   32  Bangalore
1  Rahman   22  Bangalore
2   Ayyan   42  Bangalore

In [45]:
df

     Name  Age       City  Salary
0   Abdul   32  Bangalore   50000
1  Rahman   22  Bangalore   60000
2   Ayyan   42  Bangalore   70000

In [46]:
df.drop('Salary',axis=1,inplace=True)

In [47]:
df

     Name  Age       City
0   Abdul   32  Bangalore
1  Rahman   22  Bangalore
2   Ayyan   42  Bangalore

In [48]:
## Add Age to the column
df['Age']=df['Age']+1

In [49]:
df

     Name  Age       City
0   Abdul   33  Bangalore
1  Rahman   23  Bangalore
2   Ayyan   43  Bangalore

In [50]:
df.drop(0,inplace=True)

In [51]:
df

     Name  Age       City
1  Rahman   23  Bangalore
2   Ayyan   43  Bangalore

In [52]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [54]:
print('Data types:\n',df.dtypes)

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object

In [ ]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000